recipes_project/blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
    path('', views.all_blog,name='all_blog'),
    path('<int:blog_id>/', views.detail_blog,name='detail_blog'),
]

recipes_project/component/urls.py
from django.urls import path
from . import views
app_name='recipe'
urlpatterns = [
    path('', views.all_recipes,name='all_recipes'),
    path('<int:recipe_id>/', views.detail_recipe,name='detail_recipe'),
]

recipes_project/recipes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('blog/', include('blog.urls')),
    path('component/', include('component.urls')),

]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

recipes_project/blog/models.py
from django.db import models

class blog(models.Model):
    name=models.CharField(max_length=100)
    surname=models.CharField(max_length=100)
    title=models.CharField(max_length=100)
    text=models.TextField()
    image=models.ImageField(upload_to='blog/images/')
    date=models.DateField()

    def __str__(self):
        return self.title

recipes_project/component/models.py
from django.db import models

class recipes(models.Model):
    name=models.CharField(max_length=100)
    author=models.CharField(max_length=150)
    cooking_time=models.IntegerField()
    description=models.TextField()
    image=models.ImageField(upload_to='recipes/images/')
    date=models.DateField()

    def __str__(self):
        return self.name

recipes_project/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import blog as Blog

def home(request):
    return render(request,'blog/home.html')

def all_blog(request):
    blogs=Blog.objects.all()
    return render(request,'blog/all_blog.html',{'blogs':blogs})

def detail_blog(request,blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail_blog.html',{'blog':blog})

recipes_project/component/views.py
from django.shortcuts import render, get_object_or_404
from .models import recipes as Recipes

def all_recipes(request):
    recipes=Recipes.objects.all()
    return render(request,'component/all_recipes.html',{'recipes':recipes})
def detail_recipe(request,recipe_id):
    recipe=get_object_or_404(Recipes,pk=recipe_id)
    return render(request,'component/detail_recipe.html',{'recipe':recipe})

recipes_project/blog/templates/blog/all_blog.html
{% extends 'blog/base_templates.html' %}

{% block content %}
<title>Блоги</title>
{% for blog in blogs %}
{% if blog.name %}
<div>
    <form action="{% url 'blog:detail_blog' blog.id %}">
    <input type="submit" value="{{blog.title}}">
</form>
    Автор:{{ blog.name }} {{blog.surname}}<br>
    <p>{{blog.text|truncatechars:99}}</p>
    <img src="{{blog.image.url}}">
    <p>{{blog.date}}</p>
</div>
    {% endif %}
    {% endfor %}
<form action="{% url 'recipe:all_recipes' %}">
    <input type="submit" value="До рецептів">
</form>
<form action="{% url 'home' %}">
    <input type="submit" value="На головну">
</form>
{% endblock %}

recipes_project/blog/templates/blog/base_templates.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">


  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>


  </body>
</html>

recipes_project/blog/templates/blog/detail_blog.html
{% extends 'blog/base_templates.html' %}

{% block content %}
    <title>{{blog.title}}</title>

<div>
    Автор:{{ blog.name }} {{blog.surname}}<br>
    <p>{{blog.text}}</p>
    <img src="{{blog.image.url}}">
    <p>{{blog.date}}</p>
</div>
<form action="{% url 'recipe:all_recipes' %}">
    <input type="submit" value="До рецептів">
</form>
<form action="{% url 'blog:all_blog' %}">
    <input type="submit" value="До блогу">
</form>
<form action="{% url 'home' %}">
    <input type="submit" value="На головну">
</form>

{% endblock %}

recipes_project/blog/templates/blog/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Рецепти</title>
</head>
<body>
Приувет

<div><img src="{% static 'blog\1234.jpg' %}" height="200" width="400">
<form action="{% url 'blog:all_blog' %}">
    <input type="submit" value="До блогу">
</form>
<form action="{% url 'recipe:all_recipes' %}">
    <input type="submit" value="До рецептів">
</form>
    </div>
</body>
</html>

recipes_project/component/templates/component/all_recipes.html
{% extends 'blog/base_templates.html' %}

{% block content %}
<title>Рецепти</title>
Рецепти
{% for recipe in recipes %}
{% if recipe.name %}
<div>
    <form action="{% url 'recipe:detail_recipe' recipe.id %}">
    <input type="submit" value="{{recipe.name}}">
</form>
    <p>Автор рецепту : {{recipe.author}}</p>
    <p>Час готування {{recipe.cooking_time}} хвилин</p>
    <p>{{recipe.description|truncatechars:99}}</p>
    <img src="{{recipe.image.url}}">
    <p>{{recipe.date}}</p>
    <hr color="#0000dd"/>
</div>
    {% endif %}
    {% endfor %}
<form action="{% url 'blog:all_blog' %}">
    <input type="submit" value="До блогу">
</form>
<form action="{% url 'home' %}">
    <input type="submit" value="На головну">
</form>
{% endblock %}

recipes_project/component/templates/component/detail_recipe.html
{% extends 'blog/base_templates.html' %}

{% block content %}
    <title>{{recipe.name}}</title>

<p>Автор рецепту : {{recipe.author}}</p>
    <p>Час готування {{recipe.cooking_time}} хвилин</p>
    <p>{{recipe.description|truncatechars:99}}</p>
    <img src="{{recipe.image.url}}">
    <p>{{recipe.date}}</p>
<form action="{% url 'recipe:all_recipes' %}">
    <input type="submit" value="До рецептів">
</form>
<form action="{% url 'blog:all_blog' %}">
    <input type="submit" value="До блогу">
</form>
<form action="{% url 'home' %}">
    <input type="submit" value="На головну">
</form>
{% endblock %}